### ISSUE TITLE
exportallextension.theinformationlab.io took too long to respond.

### ISSUE THREAD

**Issue by HSJD19** [TheInformationLab/Tableau-Extension-ExportAll#96] opened 2021-07-27 15:12 UTC
Today all my dashboards with the Export All extensions are giving this error exportallextension.theinformationlab.io took too long to respond.

**Comment by andre347** [comment] 2022-06-06 09:36
Closing this as I can't reproduce this.

**Closed as completed** 2022-06-06 09:35 UTC
