### ISSUE TITLE
New/Renamed sheets & fields not reflected 

### ISSUE THREAD

**Issue by tramtrax** [TheInformationLab/Tableau-Extension-ExportAll#24] opened 2019-12-02 04:15 UTC
When a new sheet is added, or an existing one is renamed, the change doesn't get reflected in the extension configurations.
Same for new/renamed fields in sheets.

Not sure if the 'Reset' button is supposed to do this - but doesn't seem so.
The only way I've found around this so far is to re-add the extension to the dashboard and set all the configurations again.
Would be great if such changes could get propagated through.

Currently using with Tableau 2019.2.2

**Comment by leefinar** [comment] 2020-02-13 15:30
I agree with you.  I added the same issue just now and then found yours.

**Comment by psuanm5030** [comment] 2020-02-14 13:33
Yeah, this one is a real pain in the but because I have to go through alot of renaming and settings configuration when I take off and put back on.  Obviously i try to minimize this but its inevitable.

**Comment by craigbloodworth** [comment] 2020-08-26 15:51
Duplicate of #31

**Closed by craigbloodworth** 2020-08-26 15:51 UTC
