### ISSUE TITLE
Unable to change order of columns

### ISSUE THREAD

**Issue by steffidhingra** [TheInformationLab/Tableau-Extension-ExportAll#60] opened 2020-08-27 10:34 UTC
Hi, I am using Tableau 2020.2.2. Export all extension is not working properly. Extension published on server on existing dashboards gets greyed out and for few dashboards, order of columns gets changed on server and few columns got duplicated with same name but does not showing any data when downloaded in excel.
For greyed out dashboards, i had to click on Reset and again added all sheets and columns.
But in one of the dashboard where sort order changes and duplicated columns added. I did reset and duplicated columns are not coming now but i am unable to change order of columns. After Saving, when i again click on Configure, sort order disturbs.

**Comment by steffidhingra** [comment] 2020-08-27 10:39
@craigbloodworth , can you please help.

**Comment by craigbloodworth** [comment] 2020-08-27 14:03
@steffidhingra this may be a duplicate of issues seen in #59 

The latest fix has been reported to fix one user's ordering issue. Could you please check to see whether yours is fixed too?

**Comment by Rahulhgupta** [comment] 2020-08-27 14:29
@craigbloodworth column order issue still not resolved.
I set the column order and saved it. Again open the configure, order is disturbed.

**Comment by HSJD19** [comment] 2020-08-27 15:39
I am seeing a similar behavior using 2019.4.10 Desktop

**Comment by melanatech** [comment] 2020-08-27 18:12
+1 to this issue, but also issue #58. I downloaded the new extension file after you closed the issue and had to re-configure the button several times before I realized the order is just not going to stay. Then when finally re-uploading to Server last night, the buttons are greyed out on two of my dashboards and the page keeps refreshing on the third. The buttons look and work perfectly fine on Desktop.

I suspect that the two where it is greyed out is an issue because they were originally using the .trex file that comes from extensiongallery.tableau.com (it had a different URL than this new .trex file: https://exportallextension.theinformationlab.io/exportall.html). The third dashboard was a recent addition but the new extension isn't working on Server.

100% appreciate you working on this extension, but is there anyway you can roll back the changes or give us a way to use the old version that was working?

**Comment by craigbloodworth** [comment] 2020-08-27 18:54
Is anybody able to provide a packaged workbook replicating the issue? If so I'll happily provide a location to securely upload it

**Comment by HSJD19** [comment] 2020-08-27 18:57
@craigbloodworth  I have something I can send you

**Comment by craigbloodworth** [comment] 2020-08-27 19:56
This is an upload only [file drop](https://fileshare.theinformationlab.co.uk/index.php/s/puLCy00gDHKr67D)

**Comment by HSJD19** [comment] 2020-08-27 20:40
@craigbloodworth  sent you a few options

**Comment by craigbloodworth** [comment] 2020-08-28 08:37
@HSJD19 Thanks for the workbooks, I've managed to replicate locally and will debug today. Thanks again for your help!

**Comment by craigbloodworth** [comment] 2020-08-28 12:56
This issue should now be resolved. Please see [this comment for more info](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/issues/59#issuecomment-682439367)

If you're able to could you confirm that all is well @HSJD19 & @steffidhingra

**Comment by steffidhingra** [comment] 2020-08-28 14:34
> This issue should now be resolved. Please see [this comment for more info](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/issues/59#issuecomment-682439367)
> 
> If you're able to could you confirm that all is well @HSJD19 & @steffidhingra

@craigbloodworth , still we are facing below issues:
1. Order of columns is not getting changed. After saving, order of columns gets disturbed. Some random order is picked up. Its neither alphabetical nor data wise. 
One thing: If i am using dimension columns before measure columns, order of dimension columns remain same but issue is coming for measure value columns.
2. My sheet has 22 columns, when i select only that sheet (6 dimensions and 16 measures) , button does not work. I clicked on button but no excel sheet gets downloaded.
if i select another sheet (having 2 columns )along with 22 columns sheet then in excel, only one tab is coming : sheet having 2 columns.
Further i tried to reduce columns to 8 from 22 in my sheet, then only excel gets downloaded but that too ordering was not correct.

**Comment by craigbloodworth** [comment] 2020-08-28 14:52
> but issue is coming for measure value columns

@steffidhingra do some of those measures use quick table calculations and/or are there duplicate measures?

**Comment by steffidhingra** [comment] 2020-08-28 15:13
> > but issue is coming for measure value columns
> 
> @steffidhingra do some of those measures use quick table calculations and/or are there duplicate measures?

@craigbloodworth there are no table calculations, we are just using logical functions like ZN, NOT. Also, calculations are based on Date parameters.
There are no duplicate measures in that sheet. But we are using all columns in another sheet.
These 2 sheets are identical, only difference is that we have to show Totals , Grand totals in report. So, we created 2 sheets.
One is for visualisation and another we hide in dashboard and used in Export all extension.

**Comment by HSJD19** [comment] 2020-08-28 15:56
@craigbloodworth Something is still amiss. 
It  seems saving is not effective. I configure one order hit save and immediately reopen the config and the order is gone 
Saving of Appear or do not appear works correctly but the column order seems to have a mind of its own. 
I am having this issue even when just exporting basic Text based Dimensions

**Comment by Alahari-git** [comment] 2020-08-28 16:15
We are using tableau extension (Export to excel) in most of our dashboards. Today we noticed the sort order defaulted to alphabetic instead of a custom order that we set up initially. Seems there is a change in version. 

I tried deleting the extension from the dashboard and downloaded an updated version from the location (https://raw.githubusercontent.com/TheInformationLab/Tableau-Extension-ExportAll/master/ExportAll.trex) but still sorting order is not fixed.

is there a way we can revert back to the old version ??

Thanks for all your help.

**Comment by shafeeq-carma** [comment] 2020-08-31 05:29
We are seeing this issue on our dashboards as well. The columns are not retaining the sort order. Our Tableau version is 2020.1.1 (20201.20.0305.1738).

**Comment by HSJD19** [comment] 2020-08-31 15:02
I think it would be super useful to be able to lock into a version or at minimum role back

**Comment by feliperamirezc** [comment] 2020-08-31 22:26
+1 here, downloaded the v2.2.0 and i'm still having the issue where the columns are ordered by alphabet and not by the order y set

**Comment by craigbloodworth** [comment] 2020-09-01 10:41
Unfortunately I can't replicate the column ordering issue. I've tested with Desktop 2020.3.0 & 2020.2.4 as well as Server 2020.3.0.

Please detail steps to recreate the issue, ideally using superstore or a shared underlying dataset, making sure to include full product type & version, operating system & each configuration step taken

**Comment by HSJD19** [comment] 2020-09-01 13:27
@craigbloodworth  I am wondering if this is a data source type issue? I am actively trying to recreate the issue with SuperStore with no luck but I can recreate it with oracle and Microsoft SQL  data sources with ease . If it would be beneficial , I am happy to have a call with you and walk you through what I am seeing

**Comment by feliperamirezc** [comment] 2020-09-01 14:17
im using tableau desktop 2020.1 on mac and its having the issue, i just created a workbook with superstore sample and the moment i set the custom order and then clicked on the save button, the custom order its not saved because after i close the window i double checked if the order was really saved and i noticed that it was not saved. See the attached images
![pic_2](https://user-images.githubusercontent.com/62101731/91862689-4c44ed80-ec3c-11ea-8e2a-1aab75c2bf8f.png)
![pic_1](https://user-images.githubusercontent.com/62101731/91862699-4ea74780-ec3c-11ea-86ea-04f1045e3766.png)

**Comment by HSJD19** [comment] 2020-09-01 15:49
@craigbloodworth  Tableau Desktop 2019.4 Server 2019.4.11 

Order of events: Open Superstore, add a handful of Dimensions from 'Sample - Superstore' data source to fresh sheet. Make dashboard featuring Extension. Publish Data Source, Publish Workbook. In Published workbook, scramble column order and screenshot it - export and compare order to screenshot

TWBX and ScreenShot Attached
[ExportIssues.zip](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5157431/ExportIssues.zip)
![BrokenExport](https://user-images.githubusercontent.com/50425927/91875210-2f62e700-ec49-11ea-919e-40a6627d9eb8.png)

**Comment by paulanson** [comment] 2020-09-01 16:14
I am getting the same sorting issue on Tableau Desktop v 2020.1 (windows) and Tableau Server v 2020.1 (windows server).  Both with newly created Superstore file and all existing workbooks where there is a customer order / renamed columns set.  Also observe that after saving Select Columns config, if go back in again the config has been lost.

**Comment by paulanson** [comment] 2020-09-02 07:31
@craigbloodworth Craig - I have retested today using same Superstore example I did before, and the sorting is now back working on Tableau v 2020.1 (Desktop and Server).  The workbooks I have already in Server are also now back working again with the columns back in their correct sort order.  Thanks for sorting this - this is an invaluable extension.

**Comment by craigbloodworth** [comment] 2020-09-02 11:24
> @craigbloodworth Tableau Desktop 2019.4 Server 2019.4.11
> 
> Order of events: Open Superstore, add a handful of Dimensions from 'Sample - Superstore' data source to fresh sheet. Make dashboard featuring Extension. Publish Data Source, Publish Workbook. In Published workbook, scramble column order and screenshot it - export and compare order to screenshot
> 
> TWBX and ScreenShot Attached
> [ExportIssues.zip](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5157431/ExportIssues.zip)
> ![BrokenExport](https://user-images.githubusercontent.com/50425927/91875210-2f62e700-ec49-11ea-919e-40a6627d9eb8.png)

Thank you for this example @HSJD19. I managed to replicate and it informed a fix which has now been implemented. Release v2.2.1 should now correct these issues for good.

Can you please validate the fix and I will close the issue.

**Comment by HSJD19** [comment] 2020-09-02 13:33
@craigbloodworth  It all seems to be working on my end ... thanks for getting this sorted.

**Comment by feliperamirezc** [comment] 2020-09-02 13:37
> > @craigbloodworth Tableau Desktop 2019.4 Server 2019.4.11
> > Order of events: Open Superstore, add a handful of Dimensions from 'Sample - Superstore' data source to fresh sheet. Make dashboard featuring Extension. Publish Data Source, Publish Workbook. In Published workbook, scramble column order and screenshot it - export and compare order to screenshot
> > TWBX and ScreenShot Attached
> > [ExportIssues.zip](https://github.com/TheInformationLab/Tableau-Extension-ExportAll/files/5157431/ExportIssues.zip)
> > ![BrokenExport](https://user-images.githubusercontent.com/50425927/91875210-2f62e700-ec49-11ea-919e-40a6627d9eb8.png)
> 
> Thank you for this example @HSJD19. I managed to replicate and it informed a fix which has now been implemented. Release v2.2.1 should now correct these issues for good.
> 
> Can you please validate the fix and I will close the issue.

I worked just fine for me on tableau desktop 2020.1 and server 2020.1
Thank you so much!!!

**Closed** 2020-09-03 12:52 UTC
Labels: bug

**Comment by LyleEllerbach** [comment] 2020-09-09 14:59
Quick question... is there a row limit on the Excel output?
